# Generated by Django 6.0.5 on 2026-05-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='json_file',
            field=models.FileField(blank=True, help_text='Canvas JSON saved as file on disk', null=True, upload_to='prescriptions/json/'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='canvas_json',
            field=models.TextField(blank=True, help_text='Fabric.js canvas JSON stored in DB'),
        ),
    ]
